Added Inbox and WatchList classes
Insanityandme/marketplace-backend pull request #11
Opened 2024-04-17 13:04 UTC by Senpai-paj

2024-04-19 19:05 UTC, Luxcorel requested changes
After changing the two commented lines, this PR is approved.

2024-04-19 19:05 UTC, Luxcorel commented on src/main/java/org/example/marketplacebackend/model/Inbox.java
> +  private Account account;
Change these lines to the following:
```
@ManyToOne
private Account receiver;
```

2024-04-20 13:30 UTC, Luxcorel requested changes
Almost everything is correct now, except one line that isn't fixed yet. See code comment for quick fix.

2024-04-20 13:30 UTC, Luxcorel commented on src/main/java/org/example/marketplacebackend/model/Inbox.java
> +  private Account account;
This line should still be: `private Account receiver;`

2024-04-30 09:03 UTC, merged

2024-04-30 09:03 UTC, JakobEdvardsson commented
LGTM